### ISSUE TITLE
[EN] Text Review

### ISSUE THREAD

**Issue by rCirelli** [calvitoria/how-to-create-API#1]
Hey Vitoria! Thank you for sharing another fantastic piece of content!

Please, let me point out a typo and suggest text improvements:

Typo on [Line 7](https://github.com/calvitoria/how-to-create-API/blob/121b8d7883bb634f52c4e5936728f269ab548e98/README.md?plain=1#L7) : utilise -> utilize.

<hr/>

Suggested text Improvements:

On [Line 36](https://github.com/calvitoria/how-to-create-API/blob/121b8d7883bb634f52c4e5936728f269ab548e98/README.md?plain=1#L36) :

**Original:**
for this exemple I created a src folder and a characters folder in it, with the database.js populating it. (src/characters/characters.json)

**Suggestion - improve visual and grammatical clarity:**
in this example, I created an _`src`_ folder and a _`characters`_ folder inside it, with the _`database.js`_ inside that folder.
(path: `src/characters/characters.json`)

<hr/>

On [Line 117](https://github.com/calvitoria/how-to-create-API/blob/121b8d7883bb634f52c4e5936728f269ab548e98/README.md?plain=1#L117) : 

**Original:**
after clicking in 'create app' you will be relocated to a new page, where you can choose the way you will be deploying your API.

**Suggestion:**
after clicking on 'create app' you will be redirected to a new page, where you can choose how you will be deploying your API.

<hr/>

On [Line 130](https://github.com/calvitoria/how-to-create-API/blob/121b8d7883bb634f52c4e5936728f269ab548e98/README.md?plain=1#L130) :

**Original:**
You can use the database using GET, POST, PUT, DELETE... requests to it. 

**Suggestion:**
You can use the database by sending GET, POST, PUT, DELETE... requests to it. 

<hr/>

In addition, you should check out GitHub [gists](https://gist.github.com/) feature. It's another way of sharing content on GitHub.

**Comment by calvitoria** [comment]
Hi Raphael!
I really appreciate you taking the time to assist me with this project.
I fixed everything you suggested! Once again you proved to be a important piece of my networking!! 
Loved the tip about gist btw!!
