### ISSUE TITLE
Text Review

### ISSUE THREAD

**Issue by Maysa-B** [calvitoria/how-to-create-API#2]
Hi Vitória! 
First, Congrats on this idea, it looks amazing (again).  ✨😊 

----

In line [14](https://github.com/calvitoria/how-to-create-API/blob/4a2138833ed4bfd0b93ad6b1120b8e3f9b3ade35/README.md?plain=1#L14) I found a misspelling: 

> Click here to **_acsess_** the content in inglês. 

The correct form is **_access_**. Besides that, I think it would look better if you changed **_inglês_** for **_English_**, but it's just a suggestion.

**Comment by calvitoria** [comment]
Hey Maysa! 
Thank you so much!! 
I indeed spelled it Wrong! All fixed up! Thank you again <3 !!
